In [191]:
import pandas as pd
import numpy as np

In [192]:
data_path = r'C:\Users\fadia\OneDrive\Desktop\Ody\Scripts\Transformed Data\Master Combined\Master_Sales_Data_2021-08-19_to_2025-07-22.csv'
df=pd.read_csv(data_path)

In [193]:
item = "Glenfiddich 18 Btl"
df_item = df[df['Item'] == item]
df_item

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
2204,2021-08-30 19:48:29,Glenfiddich 18 Btl,1,150.0,150.0,45,Visa Card,2021-08-30,Mon,Outdoor,Dinner,150.0
24818,2021-10-29 22:15:14,Glenfiddich 18 Btl,1,150.0,150.0,42,Visa Card,2021-10-29,Fri,Outdoor,Dinner,150.0
26063,2021-11-01 21:07:59,Glenfiddich 18 Btl,1,150.0,150.0,41,Visa Card,2021-11-01,Mon,Outdoor,Dinner,150.0
29500,2021-11-07 20:56:18,Glenfiddich 18 Btl,1,150.0,150.0,41,Visa Card,2021-11-07,Sun,Outdoor,Dinner,150.0
31701,2021-11-12 00:35:41,Glenfiddich 18 Btl,1,150.0,150.0,25,Visa Card,2021-11-11,Thu,Bar Area,Dinner,150.0
32741,2021-11-13 22:57:11,Glenfiddich 18 Btl,1,150.0,150.0,22,Amex,2021-11-13,Sat,Bar Area,Dinner,150.0
33437,2021-11-15 21:15:21,Glenfiddich 18 Btl,1,150.0,150.0,26,Amex,2021-11-15,Mon,Bar Area,Dinner,150.0
34748,2021-11-17 21:29:22,Glenfiddich 18 Btl,1,150.0,150.0,7,Cash,2021-11-17,Wed,Dining Area,Dinner,150.0
36491,2021-11-20 17:37:37,Glenfiddich 18 Btl,1,150.0,150.0,41,Amex,2021-11-20,Sat,Outdoor,Afternoon,150.0
37187,2021-11-21 21:46:12,Glenfiddich 18 Btl,1,150.0,150.0,3,Visa Card,2021-11-21,Sun,Dining Area,Dinner,150.0
43432,2021-12-03 21:03:10,Glenfiddich 18 Btl,1,150.0,150.0,42,Visa Card,2021-12-03,Fri,Outdoor,Dinner,150.0
44053,2021-12-04 21:05:49,Glenfiddich 18 Btl,1,150.0,150.0,1,Cash,2021-12-04,Sat,Dining Area,Dinner,150.0
44942,2021-12-06 22:38:00,Glenfiddich 18 Btl,1,150.0,150.0,44,Visa Card,2021-12-06,Mon,Outdoor,Dinner,150.0
46305,2021-12-09 20:16:17,Glenfiddich 18 Btl,1,150.0,150.0,44,Visa Card,2021-12-09,Thu,Outdoor,Dinner,150.0
48425,2021-12-13 18:38:55,Glenfiddich 18 Btl,1,150.0,150.0,42,Amex,2021-12-13,Mon,Outdoor,Afternoon,150.0
66048,2022-01-13 22:02:08,Glenfiddich 18 Btl,1,150.0,150.0,120,Visa Card,2022-01-13,Thu,Bar,Dinner,150.0
77828,2022-02-07 20:14:45,Glenfiddich 18 Btl,1,150.0,150.0,3,Cash,2022-02-07,Mon,Dining Area,Dinner,150.0
132817,2022-05-19 19:32:14,Glenfiddich 18 Btl,1,150.0,150.0,119,Cash,2022-05-19,Thu,Bar,Dinner,150.0
136810,2022-05-26 17:23:29,Glenfiddich 18 Btl,1,150.0,150.0,51,Visa Card,2022-05-26,Thu,Unknown Category,Afternoon,150.0
143196,2022-06-08 21:03:34,Glenfiddich 18 Btl,1,150.0,150.0,114,Cash,2022-06-08,Wed,Bar,Dinner,150.0
169714,2022-08-03 00:06:42,Glenfiddich 18 Btl,1,150.0,150.0,24,Cash,2022-08-02,Tue,Bar Area,Dinner,150.0
190219,2022-09-11 21:24:52,Glenfiddich 18 Btl,1,150.0,150.0,25,Capital-Visa,2022-09-11,Sun,Bar Area,Dinner,150.0
245723,2022-12-22 21:05:58,Glenfiddich 18 Btl,1,160.0,160.0,222,Capital-Visa,2022-12-22,Thu,Bar Area,Dinner,150.0
254073,2023-01-04 20:32:53,Glenfiddich 18 Btl,1,160.0,160.0,22,Capital-Visa,2023-01-04,Wed,Bar Area,Dinner,150.0
591304,2024-10-09 21:14:25,Glenfiddich 18 Btl,1,275.0,275.0,7,Capital-Visa,2024-10-09,Wed,Dining Area,Dinner,150.0

In [194]:
mask_date = "2023-02-16"

In [195]:
mask = (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
278608,2023-02-16 13:20:04,Amstel Half Pint,1,1.8,1.8,24,Cash,2023-02-16,Thu,Bar Area,Lunch,1.800
278609,2023-02-16 14:05:44,Amstel Pint,1,3.0,3.0,46,Capital-Visa,2023-02-16,Thu,Outdoor,Lunch,2.750
278610,2023-02-16 14:44:08,Amstel Pint,2,3.0,6.0,5,Capital-Visa,2023-02-16,Thu,Dining Area,Lunch,2.750
278611,2023-02-16 14:46:24,Torresella P.Grigio-Gls,2,3.9,7.8,21,Capital-Visa,2023-02-16,Thu,Bar Area,Lunch,3.500
278612,2023-02-16 14:46:26,Sparkling Water S,1,2.5,2.5,21,Capital-Visa,2023-02-16,Thu,Bar Area,Lunch,0.610
...,...,...,...,...,...,...,...,...,...,...,...,...
279397,2023-02-17 00:16:20,Small Water,1,1.0,1.0,22,Cash,2023-02-16,Thu,Bar Area,Dinner,0.058
279398,2023-02-17 00:16:20,Small Water,1,1.0,1.0,22,Capital-Visa,2023-02-16,Thu,Bar Area,Dinner,0.058
279399,2023-02-17 00:24:53,Negroni,3,8.0,24.0,45,Cash,2023-02-16,Thu,Outdoor,Dinner,4.000
279400,2023-02-17 00:24:57,Amstel Pint,2,5.0,10.0,45,Cash,2023-02-16,Thu,Outdoor,Dinner,2.750
279401,2023-02-17 00:31:22,Chivas Regal 12 Gls,1,7.0,7.0,25,Capital-Visa,2023-02-16,Thu,Bar Area,Dinner,3.500

In [196]:
# get top 20 most sold items = df['Item'].value_counts().head(5)
top_items = df['Item'].value_counts().head(20)
top_items

Item
Small Water                75947
Amstel Pint                69869
G Soda                     36254
Pepsi                      18345
Sparkling Water S          15281
Russian Standard Gls       14588
Mixers Lemon               13805
Spinach Dip                13459
Crudites Platter           13399
Jose Cuervo Silver Gls     10428
J.W Black Label Gls         9672
French Frise                9236
G Tonic                     8435
Jameson Gls                 8264
Amstel Half Pint            8184
Edamame                     8022
Bombay Gls                  8010
Dynamite Wasabi Shrimps     7889
Chicken Tenders             7855
Chivas Regal 12 Gls         7766
Name: count, dtype: int64

In [197]:
top_day_items = df[df['Day_Date'] == mask_date]['Item'].value_counts().head(50)
top_day_items

Item
Small Water                91
Amstel Pint                75
J.W Black Label Gls        42
G Soda                     34
Torresella P.Grigio-Gls    32
Chivas Regal 12 Gls        28
Russian Standard Gls       25
Sparkling Water S          22
G Tonic                    19
Pepsi                      17
Chicken Tenders            17
Carakale Blond Pint        16
Nachos                     15
Mixers Lemon               15
Spinach Dip                14
French Frise               14
Dynamite Wasabi Shrimps    13
Torresella Merlot-Gls      13
Amstel Half Pint           13
Jameson Gls                12
Edamame                    12
Crudites Platter           11
Jose Cuervo Silver Gls     10
Jr Classic Shiraz- Gls      9
Heineken Draft              8
Corona                      6
Grilled Haloumi             6
Mexican Santafe Salad       6
Bacardi Spiced.Gls          6
Lettuce Chicken Raps        5
Japanese Beef               5
Butterfly Shrimp            5
Classic Sliders             5
Fillet Mignon               5
Fried Calamari              4
Margarita                   4
Escallop Beef               4
Steak Sandwich              4
Crab Mango Salad            4
Mixers                      4
Salmon Tartar               4
Melted Cheese Balls         4
Brownies                    4
Gin Basil Smash Shot        4
Grey Goose Gls              3
Seven & Seven               3
Grilled Chicken Breast      3
Captain Morg Spiced.Gls     3
Jagermeister - Gls          3
Almaza                      3
Name: count, dtype: int64

In [198]:
mask_item = 'Almaza'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
278794,2023-02-16 18:03:42,Almaza,1,3.6,3.6,51,Capital-Visa,2023-02-16,Thu,Unknown Category,Afternoon,1.656
278801,2023-02-16 18:03:43,Almaza,1,3.6,3.6,51,Capital-Visa,2023-02-16,Thu,Unknown Category,Afternoon,1.656
278802,2023-02-16 18:03:43,Almaza,1,3.6,3.6,51,Capital-Visa,2023-02-16,Thu,Unknown Category,Afternoon,1.656

In [174]:
mask_item = 'Amstel Pint'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
129965,2022-05-15 12:14:38,Amstel Pint,1,3.0,3.0,115,Cash,2022-05-15,Sun,Bar,Lunch,2.75
129966,2022-05-15 12:14:38,Amstel Pint,1,3.0,3.0,115,Cash,2022-05-15,Sun,Bar,Lunch,2.75
129968,2022-05-15 12:17:37,Amstel Pint,2,3.0,6.0,115,Cash,2022-05-15,Sun,Bar,Lunch,2.75
129973,2022-05-15 13:21:33,Amstel Pint,2,3.0,6.0,2,Cash,2022-05-15,Sun,Dining Area,Lunch,2.75
129974,2022-05-15 13:36:56,Amstel Pint,1,3.0,3.0,2,Cash,2022-05-15,Sun,Dining Area,Lunch,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...
130505,2022-05-15 22:14:00,Amstel Pint,2,5.0,10.0,30,Visa Card,2022-05-15,Sun,Bar Area,Dinner,2.75
130540,2022-05-15 22:30:50,Amstel Pint,1,5.0,5.0,24,Visa Card,2022-05-15,Sun,Bar Area,Dinner,2.75
130543,2022-05-15 22:32:25,Amstel Pint,2,5.0,10.0,112,Visa Card,2022-05-15,Sun,Bar,Dinner,2.75
130551,2022-05-15 22:36:45,Amstel Pint,2,5.0,10.0,2,Amex,2022-05-15,Sun,Dining Area,Dinner,2.75
130555,2022-05-15 22:41:01,Amstel Pint,1,5.0,5.0,30,Visa Card,2022-05-15,Sun,Bar Area,Dinner,2.75

In [175]:
mask_item = 'Spinach Dip'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130100,2022-05-15 16:44:33,Spinach Dip,1,5.625,5.625,2,Cash,2022-05-15,Sun,Dining Area,Afternoon,3.875
130103,2022-05-15 16:49:06,Spinach Dip,1,5.625,5.625,5,Cash,2022-05-15,Sun,Dining Area,Afternoon,3.875
130140,2022-05-15 17:43:19,Spinach Dip,1,5.625,5.625,12,Visa Card,2022-05-15,Sun,Dining Area,Afternoon,3.875
130222,2022-05-15 19:30:27,Spinach Dip,1,7.500,7.500,10,Cash,2022-05-15,Sun,Dining Area,Dinner,3.875
130225,2022-05-15 19:34:52,Spinach Dip,1,7.500,7.500,116,Visa Card,2022-05-15,Sun,Bar,Dinner,3.875
130273,2022-05-15 20:17:09,Spinach Dip,1,7.500,7.500,49,Visa Card,2022-05-15,Sun,Outdoor,Dinner,3.875
130334,2022-05-15 20:47:57,Spinach Dip,1,7.500,7.500,110,Visa Card,2022-05-15,Sun,Bar,Dinner,3.875
130355,2022-05-15 21:01:52,Spinach Dip,1,7.500,7.500,112,Visa Card,2022-05-15,Sun,Bar,Dinner,3.875
130383,2022-05-15 21:15:02,Spinach Dip,1,7.500,7.500,20,Cash,2022-05-15,Sun,Bar Area,Dinner,3.875
130400,2022-05-15 21:24:31,Spinach Dip,1,7.500,7.500,24,Visa Card,2022-05-15,Sun,Bar Area,Dinner,3.875
130424,2022-05-15 21:37:38,Spinach Dip,1,7.500,7.500,27,Visa Card,2022-05-15,Sun,Bar Area,Dinner,3.875
130445,2022-05-15 21:45:56,Spinach Dip,2,7.500,15.000,12,Cash,2022-05-15,Sun,Dining Area,Dinner,3.875
130512,2022-05-15 22:19:17,Spinach Dip,1,7.500,7.500,30,Visa Card,2022-05-15,Sun,Bar Area,Dinner,3.875
130523,2022-05-15 22:26:16,Spinach Dip,1,7.500,7.500,7,Cash,2022-05-15,Sun,Dining Area,Dinner,3.875

In [176]:
mask_item = 'Russian Standard Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
129969,2022-05-15 13:07:14,Russian Standard Gls,1,3.6,3.6,50,Cash,2022-05-15,Sun,Outdoor,Lunch,3.0
130109,2022-05-15 17:01:36,Russian Standard Gls,1,3.6,3.6,200,Credit,2022-05-15,Sun,Complementary,Afternoon,3.0
130180,2022-05-15 18:48:17,Russian Standard Gls,1,6.0,6.0,116,Visa Card,2022-05-15,Sun,Bar,Afternoon,3.0
130202,2022-05-15 19:15:01,Russian Standard Gls,2,6.0,12.0,116,Visa Card,2022-05-15,Sun,Bar,Dinner,3.0
130300,2022-05-15 20:34:51,Russian Standard Gls,2,6.0,12.0,9,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.0
130333,2022-05-15 20:46:40,Russian Standard Gls,2,6.0,12.0,116,Visa Card,2022-05-15,Sun,Bar,Dinner,3.0
130348,2022-05-15 20:57:02,Russian Standard Gls,1,6.0,6.0,9,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.0
130374,2022-05-15 21:12:41,Russian Standard Gls,1,6.0,6.0,9,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.0
130378,2022-05-15 21:13:21,Russian Standard Gls,2,6.0,12.0,7,Cash,2022-05-15,Sun,Dining Area,Dinner,3.0
130393,2022-05-15 21:20:39,Russian Standard Gls,1,6.0,6.0,31,Cash,2022-05-15,Sun,Bar Area,Dinner,3.0
130416,2022-05-15 21:33:53,Russian Standard Gls,1,6.0,6.0,9,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.0
130451,2022-05-15 21:50:12,Russian Standard Gls,1,6.0,6.0,9,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.0
130469,2022-05-15 21:58:14,Russian Standard Gls,1,6.0,6.0,31,Cash,2022-05-15,Sun,Bar Area,Dinner,3.0
130489,2022-05-15 22:05:33,Russian Standard Gls,1,6.0,6.0,7,Cash,2022-05-15,Sun,Dining Area,Dinner,3.0
130495,2022-05-15 22:08:27,Russian Standard Gls,1,6.0,6.0,116,Visa Card,2022-05-15,Sun,Bar,Dinner,3.0

In [177]:
mask_item = 'Jose Cuervo Silver Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130364,2022-05-15 21:07:20,Jose Cuervo Silver Gls,1,5.0,5.0,3,Cash,2022-05-15,Sun,Dining Area,Dinner,3.0

In [178]:
mask_item = 'J.W Black Label Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130494,2022-05-15 22:06:56,J.W Black Label Gls,1,6.5,6.5,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5
130497,2022-05-15 22:10:16,J.W Black Label Gls,1,6.5,6.5,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5
130527,2022-05-15 22:28:09,J.W Black Label Gls,1,6.5,6.5,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5
130528,2022-05-15 22:28:10,J.W Black Label Gls,1,6.5,6.5,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5
130575,2022-05-15 23:00:04,J.W Black Label Gls,2,6.5,13.0,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5

In [179]:
mask_item = 'Jameson Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130059,2022-05-15 15:53:27,Jameson Gls,1,3.3,3.3,2,Cash,2022-05-15,Sun,Dining Area,Lunch,3.25

In [180]:
mask_item = 'Edamame'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
129967,2022-05-15 12:14:44,Edamame,1,4.2,4.2,115,Cash,2022-05-15,Sun,Bar,Lunch,4.2
130048,2022-05-15 15:38:22,Edamame,1,4.2,4.2,5,Cash,2022-05-15,Sun,Dining Area,Lunch,4.2
130114,2022-05-15 17:09:28,Edamame,1,4.2,4.2,32,Amex,2022-05-15,Sun,Bar Area,Afternoon,4.2
130149,2022-05-15 17:48:59,Edamame,1,4.2,4.2,43,Cash,2022-05-15,Sun,Outdoor,Afternoon,4.2
130373,2022-05-15 21:12:18,Edamame,2,7.0,14.0,20,Cash,2022-05-15,Sun,Bar Area,Dinner,4.2

In [181]:
mask_item = 'Lunardi Merlot-Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [182]:
mask_item = 'Chivas Regal 12 Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130337,2022-05-15 20:51:05,Chivas Regal 12 Gls,1,6.5,6.5,114,Cash,2022-05-15,Sun,Bar,Dinner,3.5
130338,2022-05-15 20:51:05,Chivas Regal 12 Gls,1,6.5,6.5,114,Cash,2022-05-15,Sun,Bar,Dinner,3.5
130399,2022-05-15 21:24:10,Chivas Regal 12 Gls,1,6.5,6.5,114,Cash,2022-05-15,Sun,Bar,Dinner,3.5
130405,2022-05-15 21:25:42,Chivas Regal 12 Gls,1,6.5,6.5,114,Cash,2022-05-15,Sun,Bar,Dinner,3.5
130407,2022-05-15 21:25:59,Chivas Regal 12 Gls,2,6.5,13.0,12,Cash,2022-05-15,Sun,Dining Area,Dinner,3.5
130430,2022-05-15 21:39:53,Chivas Regal 12 Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5
130449,2022-05-15 21:48:44,Chivas Regal 12 Gls,1,6.5,6.5,12,Cash,2022-05-15,Sun,Dining Area,Dinner,3.5
130488,2022-05-15 22:04:19,Chivas Regal 12 Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5
130509,2022-05-15 22:18:50,Chivas Regal 12 Gls,1,6.5,6.5,116,Visa Card,2022-05-15,Sun,Bar,Dinner,3.5
130589,2022-05-15 23:15:58,Chivas Regal 12 Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5

In [183]:
mask_item = 'Amstel Half Pint'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130008,2022-05-15 14:54:14,Amstel Half Pint,1,1.8,1.8,22,Visa Card,2022-05-15,Sun,Bar Area,Lunch,1.8
130052,2022-05-15 15:40:50,Amstel Half Pint,1,1.8,1.8,22,Visa Card,2022-05-15,Sun,Bar Area,Lunch,1.8
130406,2022-05-15 21:25:47,Amstel Half Pint,1,3.0,3.0,21,Visa Card,2022-05-15,Sun,Bar Area,Dinner,1.8
130475,2022-05-15 22:00:50,Amstel Half Pint,1,3.0,3.0,3,Visa Card,2022-05-15,Sun,Dining Area,Dinner,1.8
130556,2022-05-15 22:41:02,Amstel Half Pint,1,3.0,3.0,30,Visa Card,2022-05-15,Sun,Bar Area,Dinner,1.8
130557,2022-05-15 22:41:37,Amstel Half Pint,1,3.0,3.0,110,Visa Card,2022-05-15,Sun,Bar,Dinner,1.8
130558,2022-05-15 22:41:37,Amstel Half Pint,1,3.0,3.0,110,Visa Card,2022-05-15,Sun,Bar,Dinner,1.8

In [184]:
mask_item ='Lunardi P.Grigio-Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [185]:
mask_item ='Edammame'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [186]:
mask_item ='Dynamite Shrimp'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [187]:
mask_item ='Buffalo Tenders'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [188]:
mask_item ='Bombay Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130154,2022-05-15 17:54:59,Bombay Gls,1,3.9,3.9,2,Amex,2022-05-15,Sun,Dining Area,Afternoon,3.5
130189,2022-05-15 18:49:26,Bombay Gls,1,6.5,6.5,2,Amex,2022-05-15,Sun,Dining Area,Afternoon,3.5
130257,2022-05-15 20:04:22,Bombay Gls,1,6.5,6.5,2,Amex,2022-05-15,Sun,Dining Area,Dinner,3.5
130398,2022-05-15 21:22:50,Bombay Gls,1,6.5,6.5,25,Cash,2022-05-15,Sun,Bar Area,Dinner,3.5
130431,2022-05-15 21:39:55,Bombay Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5
130486,2022-05-15 22:04:16,Bombay Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5
130587,2022-05-15 23:15:54,Bombay Gls,1,6.5,6.5,10,Visa Card,2022-05-15,Sun,Dining Area,Dinner,3.5

In [189]:
mask_item ="Classic Sliders"
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
130053,2022-05-15 15:43:17,Classic Sliders,1,5.813,5.813,50,Cash,2022-05-15,Sun,Outdoor,Lunch,4.5
130195,2022-05-15 18:51:55,Classic Sliders,1,7.750,7.750,2,Amex,2022-05-15,Sun,Dining Area,Afternoon,4.5
130201,2022-05-15 19:14:03,Classic Sliders,1,7.750,7.750,2,Amex,2022-05-15,Sun,Dining Area,Dinner,4.5
130288,2022-05-15 20:25:51,Classic Sliders,1,7.750,7.750,24,Visa Card,2022-05-15,Sun,Bar Area,Dinner,4.5
130522,2022-05-15 22:26:12,Classic Sliders,1,7.750,7.750,7,Cash,2022-05-15,Sun,Dining Area,Dinner,4.5

In [190]:
mask_item ="J&B Rare Gls"
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []