In [76]:
import pandas as pd
import numpy as np

In [77]:
data_path = r'C:\Users\fadia\OneDrive\Desktop\Ody\Scripts\Transformed Data\Master Combined\Master_Sales_Data_2021-08-19_to_2025-07-22.csv'
df=pd.read_csv(data_path)
df.drop_duplicates(inplace=True, keep='first')

In [78]:
item = "Glenfiddich 18 Btl"
df_item = df[df['Item'] == item]
df_item

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
2204,2021-08-30 19:48:29,Glenfiddich 18 Btl,1,150.0,150.0,45,Visa Card,2021-08-30,Mon,Outdoor,Dinner,150.0
24818,2021-10-29 22:15:14,Glenfiddich 18 Btl,1,150.0,150.0,42,Visa Card,2021-10-29,Fri,Outdoor,Dinner,150.0
26063,2021-11-01 21:07:59,Glenfiddich 18 Btl,1,150.0,150.0,41,Visa Card,2021-11-01,Mon,Outdoor,Dinner,150.0
29500,2021-11-07 20:56:18,Glenfiddich 18 Btl,1,150.0,150.0,41,Visa Card,2021-11-07,Sun,Outdoor,Dinner,150.0
31701,2021-11-12 00:35:41,Glenfiddich 18 Btl,1,150.0,150.0,25,Visa Card,2021-11-11,Thu,Bar Area,Dinner,150.0
32741,2021-11-13 22:57:11,Glenfiddich 18 Btl,1,150.0,150.0,22,Amex,2021-11-13,Sat,Bar Area,Dinner,150.0
33437,2021-11-15 21:15:21,Glenfiddich 18 Btl,1,150.0,150.0,26,Amex,2021-11-15,Mon,Bar Area,Dinner,150.0
34748,2021-11-17 21:29:22,Glenfiddich 18 Btl,1,150.0,150.0,7,Cash,2021-11-17,Wed,Dining Area,Dinner,150.0
36491,2021-11-20 17:37:37,Glenfiddich 18 Btl,1,150.0,150.0,41,Amex,2021-11-20,Sat,Outdoor,Afternoon,150.0
37187,2021-11-21 21:46:12,Glenfiddich 18 Btl,1,150.0,150.0,3,Visa Card,2021-11-21,Sun,Dining Area,Dinner,150.0
43432,2021-12-03 21:03:10,Glenfiddich 18 Btl,1,150.0,150.0,42,Visa Card,2021-12-03,Fri,Outdoor,Dinner,150.0
44053,2021-12-04 21:05:49,Glenfiddich 18 Btl,1,150.0,150.0,1,Cash,2021-12-04,Sat,Dining Area,Dinner,150.0
44942,2021-12-06 22:38:00,Glenfiddich 18 Btl,1,150.0,150.0,44,Visa Card,2021-12-06,Mon,Outdoor,Dinner,150.0
46305,2021-12-09 20:16:17,Glenfiddich 18 Btl,1,150.0,150.0,44,Visa Card,2021-12-09,Thu,Outdoor,Dinner,150.0
48425,2021-12-13 18:38:55,Glenfiddich 18 Btl,1,150.0,150.0,42,Amex,2021-12-13,Mon,Outdoor,Afternoon,150.0
66048,2022-01-13 22:02:08,Glenfiddich 18 Btl,1,150.0,150.0,120,Visa Card,2022-01-13,Thu,Bar,Dinner,150.0
77828,2022-02-07 20:14:45,Glenfiddich 18 Btl,1,150.0,150.0,3,Cash,2022-02-07,Mon,Dining Area,Dinner,150.0
132817,2022-05-19 19:32:14,Glenfiddich 18 Btl,1,150.0,150.0,119,Cash,2022-05-19,Thu,Bar,Dinner,150.0
136810,2022-05-26 17:23:29,Glenfiddich 18 Btl,1,150.0,150.0,51,Visa Card,2022-05-26,Thu,Unknown Category,Afternoon,150.0
143196,2022-06-08 21:03:34,Glenfiddich 18 Btl,1,150.0,150.0,114,Cash,2022-06-08,Wed,Bar,Dinner,150.0
169714,2022-08-03 00:06:42,Glenfiddich 18 Btl,1,150.0,150.0,24,Cash,2022-08-02,Tue,Bar Area,Dinner,150.0
190219,2022-09-11 21:24:52,Glenfiddich 18 Btl,1,150.0,150.0,25,Capital-Visa,2022-09-11,Sun,Bar Area,Dinner,150.0
245723,2022-12-22 21:05:58,Glenfiddich 18 Btl,1,160.0,160.0,222,Capital-Visa,2022-12-22,Thu,Bar Area,Dinner,150.0
254073,2023-01-04 20:32:53,Glenfiddich 18 Btl,1,160.0,160.0,22,Capital-Visa,2023-01-04,Wed,Bar Area,Dinner,150.0
591304,2024-10-09 21:14:25,Glenfiddich 18 Btl,1,275.0,275.0,7,Capital-Visa,2024-10-09,Wed,Dining Area,Dinner,150.0

In [79]:
mask_date = "2022-07-26"

In [80]:
mask = (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166040,2022-07-26 13:21:50,Grey Goose Gls,3,4.2,12.6,118,Amex,2022-07-26,Tue,Bar,Lunch,4.200
166041,2022-07-26 13:22:03,Sparkling Water S,1,2.5,2.5,43,Cash,2022-07-26,Tue,Outdoor,Lunch,0.610
166042,2022-07-26 13:32:06,Gordons Dry Pink Gls,1,3.6,3.6,43,Cash,2022-07-26,Tue,Outdoor,Lunch,3.600
166043,2022-07-26 13:32:08,G Pink Lemonade,1,2.5,2.5,43,Cash,2022-07-26,Tue,Outdoor,Lunch,0.353
166044,2022-07-26 13:32:12,Chef S Salad,1,6.0,6.0,43,Cash,2022-07-26,Tue,Outdoor,Lunch,4.000
...,...,...,...,...,...,...,...,...,...,...,...,...
166417,2022-07-26 23:16:00,Sparkling Water S,1,2.5,2.5,41,Cash,2022-07-26,Tue,Outdoor,Dinner,0.610
166418,2022-07-26 23:16:00,Sparkling Water S,1,2.5,2.5,41,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,0.610
166419,2022-07-26 23:18:20,Jagermeister - Gls,2,6.0,12.0,12,Cash,2022-07-26,Tue,Dining Area,Dinner,3.000
166420,2022-07-26 23:18:49,G Soda,1,2.5,2.5,43,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,0.357
166421,2022-07-26 23:40:28,Jagermeister - Gls,2,6.0,12.0,12,Cash,2022-07-26,Tue,Dining Area,Dinner,3.000

In [81]:
# get top 20 most sold items = df['Item'].value_counts().head(5)
top_items = df['Item'].value_counts().head(20)
top_items

Item
Small Water                68212
Amstel Pint                67134
G Soda                     33648
Pepsi                      17986
Sparkling Water S          14835
Russian Standard Gls       14088
Mixers Lemon               13714
Spinach Dip                13432
Crudites Platter           13323
Jose Cuervo Silver Gls      9947
J.W Black Label Gls         9349
French Frise                9153
G Tonic                     8229
Edamame                     7991
Amstel Half Pint            7948
Jameson Gls                 7927
Dynamite Wasabi Shrimps     7862
Chicken Tenders             7840
Bombay Gls                  7774
Chivas Regal 12 Gls         7486
Name: count, dtype: int64

In [82]:
top_day_items = df[df['Day_Date'] == mask_date]['Item'].value_counts().head(50)
top_day_items

Item
Amstel Pint                  44
Small Water                  27
Margarita                    17
G Soda                       13
Pepsi                        12
Spinach Dip                  11
Russian Standard Gls         11
Sparkling Water S            11
Japanese Beef                10
Peroni Btl                    9
Dynamite Wasabi Shrimps       8
Edamame                       8
Jr Classic Chard-Gls          7
Crab Mango Salad              7
Petra Gluten Free             7
Jose Cuervo Silver Gls        6
Stolichnaya Red 75Cl/Gls      6
Bombay Gls                    6
Smirnoff Mosco Mule           6
Gin Basil Smash Shot          5
Chicken Tenders               5
Sarmientos Sauvignon-Gls      4
Fried Calamari                4
Bottega Proseco 20 Cl-Btl     4
Carakale Blond Pint.Offer     4
Whispering Angel- Btl         4
Lettuce Chicken Raps          4
Odyssey Old Fasion Shot       4
Classic Sliders               4
Chef S Salad                  4
Grey Goose Gls                3
Chinese Chicken Balls         3
Quesadilla Rolls.Chicken      3
Warm Brie Cheese              3
Mixers Lemon                  3
G Pink Lemonade               3
Gordons Dry Pink Gls          3
Mixed Sashimi                 3
Mojito Virgen                 3
Rose Tarabaca-Gls             3
Jack Danials Fire- Gls        2
Crudites Platter              2
G Bitter Lemon                2
Chicken Skewers               2
Jagermeister - Gls            2
J.W Black Label Gls           2
Amstel Btl                    2
Espresso                      2
Nachos                        2
Danzante Pinot Grigio-Btl     2
Name: count, dtype: int64

In [83]:
mask_item = 'Almaza'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [84]:
mask_item = 'Amstel Pint'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166048,2022-07-26 13:52:51,Amstel Pint,1,3.0,3.0,49,Cash,2022-07-26,Tue,Outdoor,Lunch,2.75
166051,2022-07-26 14:01:26,Amstel Pint,1,3.0,3.0,118,Cash,2022-07-26,Tue,Bar,Lunch,2.75
166073,2022-07-26 14:26:53,Amstel Pint,1,3.0,3.0,51,Cash,2022-07-26,Tue,Unknown Category,Lunch,2.75
166075,2022-07-26 14:35:00,Amstel Pint,1,3.0,3.0,118,Cash,2022-07-26,Tue,Bar,Lunch,2.75
166076,2022-07-26 14:35:44,Amstel Pint,1,3.0,3.0,52,Cash,2022-07-26,Tue,Unknown Category,Lunch,2.75
166080,2022-07-26 14:40:21,Amstel Pint,1,3.0,3.0,51,Cash,2022-07-26,Tue,Unknown Category,Lunch,2.75
166088,2022-07-26 15:03:28,Amstel Pint,1,3.0,3.0,118,Cash,2022-07-26,Tue,Bar,Lunch,2.75
166094,2022-07-26 15:17:27,Amstel Pint,1,3.0,3.0,51,Cash,2022-07-26,Tue,Unknown Category,Lunch,2.75
166097,2022-07-26 15:23:42,Amstel Pint,2,3.0,6.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Lunch,2.75
166099,2022-07-26 15:37:16,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Lunch,2.75
166100,2022-07-26 15:38:59,Amstel Pint,1,3.0,3.0,118,Cash,2022-07-26,Tue,Bar,Lunch,2.75
166101,2022-07-26 15:39:19,Amstel Pint,1,3.0,3.0,52,Cash,2022-07-26,Tue,Unknown Category,Lunch,2.75
166105,2022-07-26 15:52:07,Amstel Pint,1,3.0,3.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Lunch,2.75
166106,2022-07-26 15:54:34,Amstel Pint,1,3.0,3.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Lunch,2.75
166107,2022-07-26 15:54:55,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Lunch,2.75
166109,2022-07-26 16:02:00,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166112,2022-07-26 16:18:55,Amstel Pint,1,3.0,3.0,4,Cash,2022-07-26,Tue,Dining Area,Afternoon,2.75
166113,2022-07-26 16:20:36,Amstel Pint,3,3.0,9.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166114,2022-07-26 16:26:03,Amstel Pint,3,3.0,9.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166119,2022-07-26 16:38:11,Amstel Pint,1,3.0,3.0,118,Cash,2022-07-26,Tue,Bar,Afternoon,2.75
166124,2022-07-26 16:49:06,Amstel Pint,1,3.0,3.0,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,2.75
166127,2022-07-26 16:51:17,Amstel Pint,1,3.0,3.0,52,Cash,2022-07-26,Tue,Unknown Category,Afternoon,2.75
166131,2022-07-26 16:53:18,Amstel Pint,1,3.0,3.0,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,2.75
166138,2022-07-26 16:56:58,Amstel Pint,1,3.0,3.0,22,Capital-Visa,2022-07-26,Tue,Bar Area,Afternoon,2.75
166146,2022-07-26 17:04:39,Amstel Pint,2,3.0,6.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166147,2022-07-26 17:06:16,Amstel Pint,3,3.0,9.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166148,2022-07-26 17:07:52,Amstel Pint,1,3.0,3.0,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,2.75
166164,2022-07-26 17:32:34,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166169,2022-07-26 17:37:21,Amstel Pint,1,3.0,3.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166170,2022-07-26 17:37:29,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166171,2022-07-26 17:37:41,Amstel Pint,2,3.0,6.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166175,2022-07-26 17:42:51,Amstel Pint,1,3.0,3.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166181,2022-07-26 17:51:48,Amstel Pint,2,3.0,6.0,41,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166190,2022-07-26 17:59:56,Amstel Pint,1,3.0,3.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166200,2022-07-26 18:24:37,Amstel Pint,4,5.0,20.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,2.75
166217,2022-07-26 18:41:22,Amstel Pint,1,5.0,5.0,119,Capital-Visa,2022-07-26,Tue,Bar,Afternoon,2.75
166236,2022-07-26 19:06:19,Amstel Pint,4,5.0,20.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,2.75
166249,2022-07-26 19:22:32,Amstel Pint,1,5.0,5.0,119,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75
166254,2022-07-26 19:37:54,Amstel Pint,1,5.0,5.0,119,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75
166258,2022-07-26 19:49:54,Amstel Pint,1,5.0,5.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,2.75
166305,2022-07-26 20:46:14,Amstel Pint,1,5.0,5.0,112,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75
166349,2022-07-26 21:35:46,Amstel Pint,1,5.0,5.0,112,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75
166390,2022-07-26 22:20:36,Amstel Pint,1,5.0,5.0,112,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75
166406,2022-07-26 22:54:16,Amstel Pint,1,5.0,5.0,112,Capital-Visa,2022-07-26,Tue,Bar,Dinner,2.75

In [85]:
mask_item = 'Spinach Dip'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166059,2022-07-26 14:03:50,Spinach Dip,1,5.625,5.625,3,Capital-Visa,2022-07-26,Tue,Dining Area,Lunch,3.875
166126,2022-07-26 16:50:55,Spinach Dip,1,5.625,5.625,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.875
166134,2022-07-26 16:55:59,Spinach Dip,1,5.625,5.625,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,3.875
166142,2022-07-26 17:01:39,Spinach Dip,1,5.625,5.625,43,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.875
166151,2022-07-26 17:14:10,Spinach Dip,1,5.625,5.625,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,3.875
166212,2022-07-26 18:37:14,Spinach Dip,1,7.500,7.500,41,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.875
166255,2022-07-26 19:38:08,Spinach Dip,1,7.500,7.500,3,Cash,2022-07-26,Tue,Dining Area,Dinner,3.875
166270,2022-07-26 20:02:04,Spinach Dip,1,7.500,7.500,24,Capital-Visa,2022-07-26,Tue,Bar Area,Dinner,3.875
166292,2022-07-26 20:30:55,Spinach Dip,1,7.500,7.500,45,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,3.875
166313,2022-07-26 20:56:31,Spinach Dip,1,7.500,7.500,23,Capital-Visa,2022-07-26,Tue,Bar Area,Dinner,3.875
166318,2022-07-26 21:03:53,Spinach Dip,1,7.500,7.500,44,Cash,2022-07-26,Tue,Outdoor,Dinner,3.875

In [86]:
mask_item = 'Russian Standard Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166052,2022-07-26 14:01:47,Russian Standard Gls,2,3.6,7.2,3,Capital-Visa,2022-07-26,Tue,Dining Area,Lunch,3.0
166065,2022-07-26 14:17:51,Russian Standard Gls,2,3.6,7.2,3,Capital-Visa,2022-07-26,Tue,Dining Area,Lunch,3.0
166081,2022-07-26 14:42:26,Russian Standard Gls,2,3.6,7.2,3,Capital-Visa,2022-07-26,Tue,Dining Area,Lunch,3.0
166090,2022-07-26 15:04:14,Russian Standard Gls,1,3.6,3.6,54,Capital-Visa,2022-07-26,Tue,Unknown Category,Lunch,3.0
166092,2022-07-26 15:12:26,Russian Standard Gls,2,3.6,7.2,3,Capital-Visa,2022-07-26,Tue,Dining Area,Lunch,3.0
166095,2022-07-26 15:20:22,Russian Standard Gls,1,3.6,3.6,54,Capital-Visa,2022-07-26,Tue,Unknown Category,Lunch,3.0
166102,2022-07-26 15:41:05,Russian Standard Gls,1,3.6,3.6,54,Capital-Visa,2022-07-26,Tue,Unknown Category,Lunch,3.0
166108,2022-07-26 16:00:57,Russian Standard Gls,1,3.6,3.6,54,Capital-Visa,2022-07-26,Tue,Unknown Category,Afternoon,3.0
166117,2022-07-26 16:37:06,Russian Standard Gls,1,3.6,3.6,54,Capital-Visa,2022-07-26,Tue,Unknown Category,Afternoon,3.0
166263,2022-07-26 19:58:39,Russian Standard Gls,1,6.0,6.0,24,Capital-Visa,2022-07-26,Tue,Bar Area,Dinner,3.0
166323,2022-07-26 21:09:51,Russian Standard Gls,1,6.0,6.0,41,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,3.0

In [87]:
mask_item = 'Jose Cuervo Silver Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166115,2022-07-26 16:26:07,Jose Cuervo Silver Gls,1,3.0,3.0,47,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.0
166144,2022-07-26 17:03:41,Jose Cuervo Silver Gls,2,3.0,6.0,43,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.0
166152,2022-07-26 17:15:56,Jose Cuervo Silver Gls,1,3.0,3.0,22,Capital-Visa,2022-07-26,Tue,Bar Area,Afternoon,3.0
166168,2022-07-26 17:37:09,Jose Cuervo Silver Gls,2,3.0,6.0,43,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.0
166186,2022-07-26 17:55:24,Jose Cuervo Silver Gls,2,3.0,6.0,43,Capital-Visa,2022-07-26,Tue,Outdoor,Afternoon,3.0
166261,2022-07-26 19:53:26,Jose Cuervo Silver Gls,1,5.0,5.0,43,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,3.0

In [88]:
mask_item = 'J.W Black Label Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166272,2022-07-26 20:09:01,J.W Black Label Gls,1,3.9,3.9,119,Capital-Visa,2022-07-26,Tue,Bar,Dinner,3.5
166273,2022-07-26 20:09:01,J.W Black Label Gls,3,3.9,11.7,119,Capital-Visa,2022-07-26,Tue,Bar,Dinner,3.5

In [89]:
mask_item = 'Jameson Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [90]:
mask_item = 'Edamame'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166199,2022-07-26 18:19:50,Edamame,1,7.0,7.0,3,Cash,2022-07-26,Tue,Dining Area,Afternoon,4.2
166290,2022-07-26 20:24:53,Edamame,1,7.0,7.0,25,Cash,2022-07-26,Tue,Bar Area,Dinner,4.2
166291,2022-07-26 20:25:21,Edamame,1,7.0,7.0,21,Capital-Visa,2022-07-26,Tue,Bar Area,Dinner,4.2
166294,2022-07-26 20:31:08,Edamame,1,7.0,7.0,45,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,4.2
166328,2022-07-26 21:18:31,Edamame,2,7.0,14.0,49,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,4.2
166351,2022-07-26 21:37:55,Edamame,1,7.0,7.0,43,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,4.2
166364,2022-07-26 21:54:13,Edamame,1,7.0,7.0,41,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,4.2
166365,2022-07-26 21:54:13,Edamame,1,7.0,7.0,41,Cash,2022-07-26,Tue,Outdoor,Dinner,4.2

In [91]:
mask_item = 'Lunardi Merlot-Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [92]:
mask_item = 'Chivas Regal 12 Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [93]:
mask_item = 'Amstel Half Pint'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [94]:
mask_item ='Lunardi P.Grigio-Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [95]:
mask_item ='Edammame'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [96]:
mask_item ='Dynamite Shrimp'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [97]:
mask_item ='Buffalo Tenders'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

Empty DataFrame
Columns: [Date, Item, Quantity, Price, Total_Price, Table, Payment, Day_Date, Weekday_Name, Table_Type, Period, Cost_Price]
Index: []

In [98]:
mask_item ='Bombay Gls'
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166206,2022-07-26 18:30:53,Bombay Gls,1,6.5,6.5,5,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,3.5
166233,2022-07-26 18:59:43,Bombay Gls,1,6.5,6.5,5,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,3.5
166300,2022-07-26 20:44:43,Bombay Gls,1,6.5,6.5,12,Cash,2022-07-26,Tue,Dining Area,Dinner,3.5
166332,2022-07-26 21:23:00,Bombay Gls,1,6.5,6.5,12,Cash,2022-07-26,Tue,Dining Area,Dinner,3.5
166382,2022-07-26 22:11:21,Bombay Gls,1,6.5,6.5,46,Cash,2022-07-26,Tue,Outdoor,Dinner,3.5
166389,2022-07-26 22:19:06,Bombay Gls,1,6.5,6.5,12,Cash,2022-07-26,Tue,Dining Area,Dinner,3.5

In [99]:
mask_item ="Classic Sliders"
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166154,2022-07-26 17:19:07,Classic Sliders,1,5.813,5.813,6,Capital-Visa,2022-07-26,Tue,Dining Area,Afternoon,4.5
166271,2022-07-26 20:09:01,Classic Sliders,1,5.813,5.810,119,Capital-Visa,2022-07-26,Tue,Bar,Dinner,4.5
166374,2022-07-26 22:08:16,Classic Sliders,1,7.750,7.750,41,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,4.5
166388,2022-07-26 22:16:55,Classic Sliders,1,7.750,7.750,46,Cash,2022-07-26,Tue,Outdoor,Dinner,4.5

In [100]:
mask_item ="J&B Rare Gls"
mask = (df["Item"] == mask_item) & (df["Day_Date"] == mask_date)
df[mask]

,Date,Item,Quantity,Price,Total_Price,Table,Payment,Day_Date,Weekday_Name,Table_Type,Period,Cost_Price
166321,2022-07-26 21:06:56,J&B Rare Gls,2,6.0,12.0,41,Capital-Visa,2022-07-26,Tue,Outdoor,Dinner,3.25