In [16]:
import pandas as pd
import os
import re

In [17]:
# read the excel file
path = r"C:\Users\fadia\OneDrive\Desktop\Ody\Data\odyssey_subcategories.xlsx"
# there is no  'sheet1' in the file, changed to correct sheet name
df = pd.read_excel(path)
df.head()

  Categories Sub-categories             Item
0   Beverage           Arak  Arak Haddad Btl
1   Beverage           Arak  Arak Haddad Gls
2   Beverage           Beer     Alhambra Btl
3   Beverage           Beer           Almaza
4   Beverage           Beer      Almaza 5Btl

In [18]:
# i want to filter the dataframe to get only where 'Categories' is 'Beverage'
df_beverage = df[df['Categories'] == 'Beverage']
# capitalize the columns names
df_beverage.columns = [col.capitalize() for col in df_beverage.columns]
# capitalize the items in 'Item' column
df_beverage['Item'] = df_beverage['Item'].str.title()
df_beverage.head()

C:\Users\fadia\AppData\Local\Temp\ipykernel_24400\85766400.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_beverage['Item'] = df_beverage['Item'].str.title()

  Categories Sub-categories             Item
0   Beverage           Arak  Arak Haddad Btl
1   Beverage           Arak  Arak Haddad Gls
2   Beverage           Beer     Alhambra Btl
3   Beverage           Beer           Almaza
4   Beverage           Beer      Almaza 5Btl

In [19]:
# btl items 
btl_path = r"C:\Users\fadia\OneDrive\Desktop\Ody\Data\beverage_btl_items.xlsx"
df_btl = pd.read_excel(btl_path)
df_btl.columns = [col.capitalize() for col in df_btl.columns]
# capitalize the items in 'Item' column
df_btl['Item'] = df_btl['Item'].str.title()
df_btl.head()

                    Item
0    J.W Black Label Btl
1  Woodford Reserved Btl
2          Tanqueray Btl
3          Hendricks Btl
4  Chivas Regal Xv - Btl

In [20]:
# i want to exclude items that is in df_btl from df_beverage
beverage_items_gls = df_beverage[~df_beverage['Item'].isin(df_btl['Item'])] 
beverage_items_gls = beverage_items_gls[['Item', 'Sub-categories']]
beverage_items_gls.reset_index(drop=True, inplace=True)
beverage_items_gls.sort_values(by='Item', inplace=True)
beverage_items_gls

                        Item     Sub-categories
182       1800 Reposado- Gls            Tequila
183        1800 Silver - Gls            Tequila
34   A.Fuente Conquistadores              Cigar
35             A.Fuente Gran              Cigar
231       Aberfeldy 16Y. Gls             Whisky
..                       ...                ...
100      Totino Cherry - Gls  Cocktails & Shots
151       Totino Peach - Gls            Liqueur
283          West Cork - Gls             Whisky
101            White Russian  Cocktails & Shots
284    Woodford Reserved Gls             Whisky

[318 rows x 2 columns]

In [ ]:
# save to excel file
output_path = r"C:\Users\fadia\OneDrive\Desktop\Ody\Data\beverage_items_excluding_btl_by_gls.xlsx"
if not os.path.exists(os.path.dirname(output_path)):
    os.makedirs(os.path.dirname(output_path))
beverage_items_gls.to_excel(output_path, index=False)